@isTest
public  class updateCreditCardTestCases {
    public static testMethod void runUpdateCreditCardTestCases() {

        // String email = 'alan.feng@4idps.com';
        // String email2 = 'alan.feng2@4idps.com';

        // Account__c account = new Account__c(LastName__c = 'Alan', Email__c = email);
        // insert account;

        // System.assertNotEquals(null, account.Id);

        // UpdateCreditCardController controller = new UpdateCreditCardController();

        // Account__c controllerAccount = controller.getAccount();

        // System.assertEquals(controllerAccount.Id, account.Id);
        
        // controllerAccount.Email__c = email2;        
        // controller.submit();
        // Account__c account2 = [Select Id, Email__c from Account__c where Email__c = :email2];

        // System.assertEquals(controllerAccount.Email__c, account2.Email__c);
    }
}
