sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_96c3aa060ec9_key -iv $encrypted_96c3aa060ec9_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DevHub
script:
- sfdx force:org:create -f config/project-scratch-def.json --setalias DevCi --setdefaultusername --wait 2
- sfdx force:org:display -u DevCi
- sfdx force:source:push -u DevCi
- sfdx force:user:permset:assign --targetusername DevCi --permsetname Scratch
- sfdx force:data:tree:import -f tmp/sfdx-out/export-demo-SubscriptionProgram__cs.json
- sfdx force:data:tree:import -f tmp/sfdx-out/export-demo-Product2s.json
- sfdx force:data:tree:import -f tmp/sfdx-out/export-demo-Address__cs.json
- sfdx force:data:tree:import -f tmp/sfdx-out/export-demo-Address__cs2.json
- sfdx force:apex:test:run -u DevCi --wait 10
- sfdx force:org:delete -u DevCi -p
notifications:
  email:
    recipients:
      - jin@4idps.com
      - bruno.chami@4idps.com
      - alan.feng@4idps.com
    on_success: never # default: change
    on_failure: always # default: always
