public class Constants {
    public static String ST_CODE_CREDIT_CARD_PAYMENT = '10000-00000-00000-00000-00000-00000-00000';
    public static String ST_CODE_SUPER_PAYMENT = '00100-00000-00000-00000-00000-00000-00000';
    public static String ST_CODE_ATM = '00010-00000-00000-00000-00000-00000-00000';
    public static String ST_CODE_NOTHING = '00000-00000-00000-00000-00000-00000-00000';

    public static String PROCESS_CODE_ONE_TIME = '2';
    public static String PROCESS_CODE_REGISTER_CREDIT_CARD = '2';
    public static String PROCESS_CODE_CHANGE_CREDIT_CARD = '3';
    public static String PROCESS_CODE_DELETE_CREDIT_CARD = '10';

    public static Integer COOKIE_DURATION = -1;
}