public class GMOPaymentBean {
    public string contract_code {get; set;}
    public string version {get; set;}
    public string character_code {get; set;}
    public string process_code {get; set;}
    public string user_id {get; set;}
    public string user_name {get; set;}
    public string user_mail_add {get; set;}
    public string lang_id {get; set;}
    public string ip_address {get; set;}
    public string user_agent {get; set;}
    public string item_code {get; set;}
    public string item_name {get; set;}
    public string order_number {get; set;}
    public string st_code {get; set;}
    public string mission_code {get; set;}
    public string currency_id {get; set;}
    public string item_price {get; set;}
    public string card_number {get; set;}
    public string expire_year {get; set;}
    public string expire_month {get; set;}
    public string security_code {get; set;}
    public string pan_bank {get; set;}
    public string pan_country {get; set;}
    public string card_holder_name {get; set;}
    public string add_info1 {get; set;}

}