public class GMOPaymentCheckOrderResultBean {

    public TmpGlobalPayment_result GlobalPayment_result;

	public class TmpGlobalPayment_result {
		public String sales_id;
		public String bank_order_number;
		public String masked_card_number;
		public String installment_period;
		public String auth_date;
		public String unique_trans_cd;
		public String auth_code;
		public String charge_date;
		public String payment_code;
		public String receipt_date;
		public String memo2;
		public String memo1;
		public String item_price;
		public String currency_id;
		public String mission_code;
		public String st_code;
		public String trans_code;
		public String order_number;
		public String item_name;
		public String item_code;
		public String lang_id;
		public String user_mail_add;
		public String user_name;
		public String user_id;
		public String state;
		public String process_code;
		public String character_code;
		public String version;
		public String contract_code;
        public String consumer_phone;
        public String serial_number;
        public String writeoff_number;
        public String other_01;
        public String other_02;
        public String other_03;
        
	}
}